### ISSUE TITLE
On Windows (Firefox), typing 'type Footballer' or 'class dist' removes ' ' from search text box

### ISSUE THREAD

**Issue by peterachten** [clean-cloogle/Cloogle#15]
On Windows 10 (Firefox), typing the query 'type Footballer' or 'class dist' removes ' ' from search text box, so that you end up with 'typeFootballer' and 'classdist'.

This does not happen with Microsoft Edge nor Chrome.

**Comment by dopefishh** [comment]
The highlighter appears to output correct code:
```
highlightQuery('type Footballer')
"<span class=\"keyword\">type</span><span class=\"whitespace\"> </span><span class=\"type\">Footballer</span>"
```

So it probably has something to do with the input field mangling it.

**Comment by camilstaps** [comment]
This issue was moved to clean-cloogle/cloogle.org#210
