### ISSUE TITLE
On Windows (Microsoft Edge), selecting entire query and press 'Delete' makes query text box go away

### ISSUE THREAD

**Issue by peterachten** [clean-cloogle/Cloogle#16]
On Windows 10, using Microsoft Edge, if you have entered a text in the query text box, and then select it from start to end (for instance by pressing 'Home' followed by 'Shift'+'End', and then press 'Delete' makes the entire text box go away. Refreshing the page makes it visible again. 

This does not happen with Firefox nor Chrome.

**Comment by camilstaps** [comment]
This issue was moved to clean-cloogle/cloogle.org#211

**Comment by dopefishh** [comment]
Can confirm, the whole textfield seems borked.
I'm not sure whether we should support all browsers. Firefox and Chrome ought
to be enough right?
