### ISSUE TITLE
Cloogle does not seem to find entries from SoccerFun

### ISSUE THREAD

**Issue by peterachten** [clean-cloogle/Cloogle#17]
On Windows, independent from browser, having selected the StdEnv and SoccerFun library in the Miscelleneous section, does not seem to find entries from SoccerFun. Attempted queries: 'type Footballer' and 'class dist'.

**Comment by camilstaps** [comment]
You need to enable "include apps" in the advanced search options. Results from SoccerFun, clean-compiler, clean-ide and other applications are hidden by default as they are not useful unless you are working on that particular application.

**Comment by peterachten** [comment]
Ah, I see. I notice that if you hover the mouse sufficiently long over the `(app)` description, you actually get a notice that tells you that you might want to tick the `include apps` box. However, my attention got distracted because almost as soon as you hover the mouse over the `(app)` description, an `i` marker shows up, which led me to click on that, showing the `SoccerFun` homepage. After that, I didn't go back to the `(app)` description.

How feasible would it be that if a user selects a category that requires `(app)`, to also select the `Include apps` option? Or perhaps, change the text of `(app)` into `(requires Include apps)`?

**Comment by camilstaps** [comment]
This issue was moved to clean-cloogle/cloogle.org#212
