### ISSUE TITLE
Race condition in the statistics?

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle#22]
It seems that under heavy traffic the same timestamp is added twice on /stats (Firefox 46.0.1):

![](http://i.stack.imgur.com/QSfuw.png)

According to [this](http://stackoverflow.com/a/7868445/1544337), JavaScript isn't threaded. However, it _is_ a post from 2011...

**Comment by dopefishh** [comment]
I propose to drop the heavy nodeJS dependency and to use something like websocketd to get rid of this.
