### ISSUE TITLE
Add fix arity option

### ISSUE THREAD

**Issue by dopefishh** [clean-cloogle/cloogle#28]
This decreases the search space for unification and is often what the user wants. By default this should be off

**Comment by camilstaps** [comment]
- If we resolve #27, does this become obsolete?
- I'm not sure if this is easily possible; before unification we rewrite all functions to arity 1 (as in Haskell style)

**Comment by camilstaps** [comment]
I feel like we don't really need this, because [the distance measure](https://github.com/clean-cloogle/cloogle/blob/master/backend/CloogleServer.icl#L402) takes care that arguments unified with a function get a high distance.
