### ISSUE TITLE
Library browser in src/view.php 

### ISSUE THREAD

**Issue by camilstaps** [clean-cloogle/cloogle#90]
src/view.php could be given a sidebar with a library browser. It could display the whole library as a tree, possibly also adding an option to switch libraries. And, of course, an option to switch icl/dcl.

Then we could link to this page also from library names, e.g. 'Platform' in a search result could link to the page which does not open any source code but still has the side bar to browse Platform.

**Comment by dopefishh** [comment]
Definitly a good idea

**Comment by camilstaps** [comment]
Still to do:

- Automatically open library until current module
- Highlight current module (italics?)
