### ISSUE TITLE
ClassResultExtras.class_funs inconsistent values

### ISSUE THREAD

**Issue by KDercksen** [clean-cloogle/cloogle#95]
`ClassResultExtras.class_funs` should hold a list of values, but in specific instances holds a newline-separated string with values. To reproduce:

    Correct:
    https://cloogle.org/api.php?str=class List
    class_funs = ["_cons :: .e u:(l .e) -> u:(l .e)","_decons :: !u:(l .e) -> (.e,u:(l .e))"]
                                                    ^

    Incorrect:
    https://cloogle.org/api.php?str=class Eq
    class_funs = ["(<>) infix 4 :: !a !a -> Bool | Eq a\n(<>) x y :== not (x == y)"]
                                                        ^

I do not believe this is intended behaviour?

**Comment by camilstaps** [comment]
This is by design. There are newlines when it is a macro. The first line is the type, the second the implementation.

**Comment by KDercksen** [comment]
> This is by design. There are newlines when it is a macro. The first line is the type, the second the implementation.

Alright, my apologies :smiley:

**Comment by camilstaps** [comment]
No need :)
